const fallbackImageMap = {
  calientes: "capuchino.png",
  tesLatte: "latte.png",
  tes: "abuela.png",
  frias: "espresso.png",
  casa: "latte.png",
  bagels: "americano.png",
  hotcakes: "crepa-clasica.png",
  crepas: "crepa-cielo.png",
  comida: "americano.png",
};

const featuredSelections = [
  { categoryId: "casa", itemName: "Latte Dulce Corazon", badge: "Popular" },
  { categoryId: "frias", itemName: "Frappe Oreo", badge: "Favorito" },
  { categoryId: "calientes", itemName: "Latte Moka", badge: "Imperdible" },
];

const menuData = {
  categories: [
    { id: "todo", label: "Todo", icon: "\u2728", title: "Todo el Menu" },
    { id: "calientes", label: "Calientes", icon: "\u2615", title: "Bebidas Calientes" },
    { id: "frias", label: "Frias", icon: "\ud83e\uddca", title: "Bebidas Frias" },
    { id: "casa", label: "De la casa", icon: "\u2b50", title: "Bebidas de la Casa" },
    { id: "tes", label: "Tes", icon: "\ud83c\udf75", title: "Tes" },
    { id: "tesLatte", label: "Tes latte", icon: "\ud83c\udf75", title: "Tes Latte" },
    { id: "bagels", label: "Bagels", icon: "\ud83e\udd6f", title: "Bagels y Cuernitos" },
    { id: "hotcakes", label: "Hotcakes", icon: "\ud83e\udd5e", title: "Hotcakes" },
    { id: "crepas", label: "Crepas", icon: "\ud83e\uded3", title: "Crepas" },
    { id: "comida", label: "Comida", icon: "\ud83c\udf7d", title: "Comida" },
  ],
  items: {
    calientes: [
      { nombre: "Espresso Doble", desc: "Doble carga de espresso", precio: "$40", img: "espresso.png" },
      { nombre: "Americano", desc: "Clásico", precio: "$50", img: "americano.png" },
      { nombre: "Capuchino", desc: "Espresso, leche y espuma", precio: "$65", img: "capuchino.png" },
      { nombre: "Latte Original", desc: "Espresso y leche", precio: "$65", img: "latte.png" },
      { nombre: "Latte Vainilla", desc: "Espresso, leche y vainilla", precio: "$65", img: "latte-vainilla.png" },
      { nombre: "Latte Caramelo", desc: "Espresso, leche y caramelo", precio: "$65", img: "latte-caramelo.png" },
      { nombre: "Latte Moka", desc: "Espresso, leche y chocolate", precio: "$65", img: "moka.png" },
    ],
    tesLatte: [
      { nombre: "Masala Chai Latte", desc: "Té chai, leche y vainilla", precio: "$70", img: "chai.png" },
      { nombre: "Earl Gray Latte", desc: "Té negro, leche y vainilla", precio: "$70", img: "earl.png" },
      { nombre: "Latte Matcha", desc: "Matcha, leche y vainilla", precio: "$70", img: "latte-matcha-caliente.png" },
      { nombre: "Latte Taro", desc: "Taro cremoso con leche", precio: "$70", img: "latte-taro.png" },
    ],
    tes: [
      { nombre: "Hibiscus", desc: "Té caliente", precio: "$45", img: "hibiscus.png" },
      { nombre: "Earl Gray", desc: "Té clásico", precio: "$45", img: "earl-tea.png" },
      { nombre: "Moroccan Mint", desc: "Té de menta", precio: "$45", img: "mint-te.png" },
      { nombre: "Cranberry Spice", desc: "Té especiado", precio: "$45", img: "cranberry.png" },
      { nombre: "Sencha", desc: "Té verde", precio: "$45", img: "sencha.png" },
      { nombre: "Rooibos", desc: "Té africano", precio: "$45", img: "rooibos.png" },
      { nombre: "Yerba Mate", desc: "Tradicional", precio: "$45", img: "mate.png" },
      { nombre: "Jasmine Green", desc: "Té verde jazmín", precio: "$45", img: "jasmine.png" },
    ],
    frias: [
      { nombre: "Frappe Oreo", desc: "Galleta oreo, leche y chantilly", precio: "$70", img: "frappe-oreo.png" },
      { nombre: "Frappe Gansito", desc: "Sabor gansito con leche", precio: "$70", img: "frappe-gansito.png" },
      { nombre: "Frappe Caramelo", desc: "Caramelo, espresso y leche", precio: "$70", img: "frappe-caramelo.png" },
      { nombre: "Frappe Vainilla", desc: "Espresso, leche y chantilly", precio: "$70", img: "frappe-vainilla.png" },
      { nombre: "Frappe Moka", desc: "Chocolate, espresso y leche", precio: "$70", img: "frappe-moka.png" },
      { nombre: "Frappe Taro", desc: "Taro cremoso con leche", precio: "$70", img: "frappe-taro.png" },
      { nombre: "Latte Frío Original", desc: "Café y leche sobre hielo", precio: "$65", img: "latte-frio.png" },
      { nombre: "Latte Frío Caramelo", desc: "Con caramelo", precio: "$65", img: "latte-caramelo-frio.png" },
      { nombre: "Latte Frío Moka", desc: "Con chocolate", precio: "$65", img: "latte-moka-frio.png" },
      { nombre: "Americano Frío", desc: "Café sobre hielo", precio: "$65", img: "americano-frio.png" },
      { nombre: "Latte Frío Matcha", desc: "Matcha, vainilla y leche", precio: "$65", img: "latte-matcha-frio.png" },
      { nombre: "Latte Frío Taro", desc: "Taro cremoso con leche", precio: "$65", img: "latte-taro-frio.png" },
      { nombre: "Smoothie Fresa y Plátano", desc: "Natural", precio: "$65", img: "smoothie-fresa.png" },
      { nombre: "Smoothie Piña y Mango", desc: "Refrescante", precio: "$65", img: "smoothie-mango.png" },
    ],
    casa: [
      { nombre: "Latte Dulce Corazón", desc: "Espresso, leche y leche condensada", precio: "$65", img: "latte-corazon-1.png", badge: "Popular" },
      { nombre: "Moka Zapoteco", desc: "Chocolate de la casa + mezcal", precio: "$65", img: "zapoteco.png" },
      { nombre: "Espresso Polar", desc: "Espresso doble con crema", precio: "$65", img: "polar.png" },
      { nombre: "Bubble Twister", desc: "Agua mineral, espresso y limón", precio: "$65", img: "bubble.png" },
      { nombre: "Caribe Coco", desc: "Crema de coco, espresso y leche", precio: "$65", img: "coco.png" },
    ],
    bagels: [
      { nombre: "Bagel con Queso Crema", desc: "Bagel sencillo con queso crema", precio: "$45", img: "bagel-queso-crema.png" },
      { nombre: "Bagel Sandwich", desc: "Mayonesa, lechuga, tomate, jamón y queso manchego", precio: "$60", img: "bagel-sandwich.png" },
      { nombre: "Cuernito con Queso Manchego", desc: "Cuernito con queso manchego fundido", precio: "$40", img: "cuernito-queso-manchego.png" },
      { nombre: "Cuernito Sandwich", desc: "Mayonesa, lechuga, tomate, jamón y queso manchego", precio: "$60", img: "cuernito-sandwich.png" },
    ],
    hotcakes: [
      { nombre: "Hotcakes Plátano o Fresa", desc: "Con un endulzante a elegir", precio: "$55", img: "hotcakes-platano-o-fresa.png" },
      { nombre: "Hotcakes Plátano y Fresa", desc: "Con un endulzante a elegir", precio: "$60", img: "hotcakes-platano-fresa.png" },
    ],
    crepas: [
      { nombre: "Crepa Cielo", desc: "Manzana caramelizada", precio: "$65", img: "crepa-cielo.png" },
      { nombre: "Crepa Moka Moka", desc: "Chocolate y plátano", precio: "$65", img: "crepa-moka.png" },
      { nombre: "Crepa Queso Crema", desc: "Fresa o zarzamora", precio: "$55", img: "crepa-queso.png" },
      { nombre: "Crepa Clásica", desc: "Plátano, fresa y nutella", precio: "$65", img: "crepa-clasica.png" },
      { nombre: "Crepa Personalizada", desc: "Endulzante a elegir", precio: "$65", img: "crepa-personalizada.png" },
      { nombre: "Crepa Salada Jamón", desc: "Queso manchego y jamón", precio: "$65", img: "crepa-jamon.png" },
      { nombre: "Crepa Champiñones Jamón", desc: "Queso manchego, champiñones y jamón", precio: "$65", img: "crepa-champ.png" },
      { nombre: "Crepa Champiñones Salchicha", desc: "Queso y salchicha", precio: "$65", img: "crepa-salchicha.png" },
      { nombre: "Crepa Pepperoni", desc: "Queso y pepperoni", precio: "$65", img: "crepa-pepperoni.png" },
    ],
    comida: [
      { nombre: "Leandrini Panini", desc: "Pollo, jalapeño, queso y verduras", precio: "$100", img: "panini-leandrini.png" },
      { nombre: "Panini Chipotle", desc: "Pollo, chipotle y queso", precio: "$100", img: "panini-chipotle.png" },
      { nombre: "Panini Pesto", desc: "Pollo, pesto y queso", precio: "$100", img: "panini-pesto.png" },
      { nombre: "Quesadilla", desc: "Pollo, frijoles, queso y salsas", precio: "$90", img: "quesadilla.png" },
      { nombre: "Ensalada Zapoteca", desc: "Pollo, frijoles, elote, tortillas y salsa zapoteca", precio: "$90", img: "ensalada-zapoteca.png" },
      { nombre: "Hotdog XL", desc: "Con verduras, aderezos y chile tatemado", precio: "$65", img: "hotdog.png" },
    ],
  },
};
